version: "3.8"

services:
  frontend:
    container_name: frontend
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  nginx:
    image: nginx:stable-alpine
    container_name: ai-chatbot-nginx
    depends_on:
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/nginx.conf
    networks:
      - ai-chatbot-network

networks:
  ai-chatbot-network:
    driver: bridge
